"""The tick pipeline's explicit query and recording boundary."""

from __future__ import annotations

from typing import Any, Protocol

from mapf.core.components import SimFrame
from mapf.core.models import Conflict, Path, Point
from mapf.core.observations import LocalEnvironment
from mapf.core.protocols import AgentProtocol, EnvironmentProtocol, NegotiatorProtocol
from mapf.telemetry.hook import TelemetryHook


class TickWorld(EnvironmentProtocol, Protocol):
    """Domain operations used by stages; no private world storage is exposed."""

    @property
    def agents(self) -> dict[str, AgentProtocol]: ...
    @property
    def negotiator(self) -> NegotiatorProtocol: ...
    @property
    def telemetry_hook(self) -> TelemetryHook: ...

    def for_agent(self, agent_id: str) -> LocalEnvironment: ...
    def observation_snapshot(self) -> dict[str, Any]: ...
    def detect_conflicts(self, *, paths: dict[str, Path], goals: dict[str, Point],
                         current_time: int, lookahead_steps: int,
                         disappear_at_target: bool) -> list[Conflict]: ...
    def record_replan(self, status: str, receipt: dict[str, Any] | None = None) -> None: ...
    def mark_unsolvable(self) -> None: ...
    def record_negotiation(self, entry: dict[str, Any]) -> None: ...
    def record_negotiation_outcome(self, reason: str) -> None: ...
    def stop_negotiation(self, reason: str, detail: dict[str, Any]) -> None: ...
    def stop_movement(self, reason: str, receipt: dict[str, Any]) -> None: ...
    def record_movement_repair(self, repair: dict[str, Any]) -> None: ...
    def record_motion(self, *, stationary: bool) -> None: ...
    def record_safety_intervention(self) -> None: ...
    def record_position(self, agent_id: str, position: Point) -> None: ...
    def drain_decision_heat(self) -> tuple[list[dict[str, Any]], int]: ...
    def finish_tick(self, frame: SimFrame) -> None: ...
