"""Reproducible contract export; no supervisor is constructed during OpenAPI generation."""

import json
from pathlib import Path

from mapf.application.contracts import JobSubmissionRequest
from mapf.application.presets import get_preset
from mapf.gui.app import create_app

ROOT = Path(__file__).resolve().parents[1]
(ROOT / "docs/gui/openapi.json").write_text(
    json.dumps(create_app().openapi(), indent=2, sort_keys=True) + "\n"
)

from mapf.telemetry.schema import EVENT_ADAPTER

(ROOT / "docs/gui/telemetry.schema.json").write_text(
    json.dumps(EVENT_ADAPTER.json_schema(), indent=2, sort_keys=True) + "\n"
)

(ROOT / "frontend/src/api/presets.generated.ts").write_text(
    '// Generated by scripts/export_gui_schema.py. Change the Python preset, then regenerate.\n'
    'import type { JobSubmissionRequest } from "./types";\n'
    'export const STARTER_INPUTS: JobSubmissionRequest = '
    + json.dumps(get_preset("interactive-v1").inputs.model_dump(mode="json", exclude_none=True), indent=2)
    + ';\n'
    + 'export const REQUEST_FIELDS = '
    + json.dumps(list(JobSubmissionRequest.model_fields), indent=2)
    + ' as const satisfies readonly (keyof JobSubmissionRequest)[];\n'
)
